### PR TITLE
First version of adding support for Debian 11 [maybe obsolete]

### PR DESCRIPTION
**Pull request by mikedlr**
This pull request will add support for Debian 11 and attempt to improve Debian 10 by removing use of the xstartup file which is currently causing incorrect session startup.

### CODE REVIEW

**Comment by sdarwin** [comment]
"Add support for Debian 11" and "attempt to improve Debian 10" are two separate issues.   They should be two different pull requests.

Debian 10 would be to modify the existing startup files, most likely.  Not a huge structural change.

Debian 11 is a major rewrite, a new version of tigervnc.  What needs to be done is outlined in some comments yesterday https://github.com/sdarwin/Ansible-VNC/pull/13#issuecomment-914754497     If you follow those sort of steps, without using the ansible role, just install tiger manually, then VNC will function on Debian 11.   It does help to refer to the package list from the role, to know which other apt packages should be installed.

In terms of Debian 11, now I am considering the possibility of getting involved, and writing the update myself.    

But, at the same time, I would also be happy to give you a chance.        

So then, not sure what to do.  :-)     

You may tell me, if you would like to tackle Debian 11, or I should step in.   Both are a possibility.   Let me know.

If you do work on it, then please do the majority of development and the testing in a different git branch, not the pull request branch.     Only submit changes in the PR when they are functional, and ready for a review.   If the vnc is still broken, it's too early to be in the pull request.

**Comment by sdarwin** [comment]
Hi @mikedlr , the Debian 11 fix is fairly critical.  We should communicate clearly about it.  

The latest thinking about the feature:

Set up two vnc_paradigms as ansible blocks in main.yml. Also, instead of entirely removing vncstop/vncstart, change their contents to use the new tigervnc systemctl commands, and sudo.  Modify sudo files so users can run those commands.   Create new /etc/tigervnc/vncserver.users  template.  The way to grok all those steps, just mentioned, is to install tigervnc manually on Debian 11, without the ansible role.  You observe how systemctl is used in the new system, to start and stop the services, and see how vncserver.users  must be configured.

Here is multiple-choice.  Which do you prefer?  either is fine.

Choice A:  mikedlr would like to re-architect tasks/main.yml, and the entire role.  test. debug. completed.   ( and,  if so, what might be an expected time frame?  )

or

Choice B:   that's a lot to do.  not exactly sure.     sdarwin could go ahead and work on it.

**Comment by mikedlr** [comment]
@sdarwin since debian 10 fix code hadn't made it into this branch I have simply renamed this PR.  It's only Debian 11. 

I think my major concern / interest here is to get a reasonably consistent setup between different distributions.  If I understand your latest proposal then I think that having the two mechanisms in place is sensible since that is more consistent with the old situation on new distributions.  

I would, I think appreciate if you go ahead with this. I will in the meantime have a look at and concentrate on the Amazon and Rocky code.  I'm trying to do other things in parallel and so I'd rather not block any development.

**Comment by sdarwin** [comment]
> I would, I think appreciate if you go ahead with this. 

Proceeding with Debian 11 then.  
Actually, the update is really tigervnc version 1.11.0.

**Comment by sdarwin** [comment]
New 'support for Debian 11' pushed to master branch.  Bug reports welcome.

**Pull request closed without merging**
