### PR TITLE
Add initial support for Amazon Linux 2 and Rocky Linux

### PR DESCRIPTION
**Pull request by mikedlr**
Partial rewrite of https://github.com/sdarwin/Ansible-VNC/pull/13 with Debian related changes removed and rebased on top of pre-commit PR.  

This PR attempts to add support for Rocky Linux and Amazon Linux including documentation and CI.

### CODE REVIEW

**Comment by sdarwin** [comment]
It would be great to click "merge".

However, it cannot be done (right?).

Because Amazon Linux 2 and Rocky Linux are mixed up in the same pull request.   If Amazon Linux is not functional, then it's a blocker.   Can't proceed.   If there were more focused PR's, for example:  


- "only cleaning up formatting".    this could be merged.
-  "only Rocky Linux".    if that's attained a functional state, it could be merged.
- etc.

**Comment by mikedlr** [comment]
So all of the above is "functional" as in useful  There's a decision to be made with the Amazon stuff, though, which is what to do about desktops.  

For Amazon, we are now using this, creating a mate desktop and setting it up outside the role.  This requires adding one file.

We also did the experiment and showed that, installing the gnome packages *does* work on AWS Linux 2.  This was done by adding gnome* 

Before I go ahead and do the work to cleanup and possible restructure into separate patches, I'd like to get your opinion on how you would like the module to work in this case?  Do you care about consistency of which desktop is provided over the different supported desktops?  Would you like Amazon to default to Gnome like other distros or would you like it to default to mate since that seems to be the AWS (more?) supported option?

**Comment by sdarwin** [comment]
> So all of the above is "functional" 

Oh, alright.  You had mentioned earlier results, that it was still buggy and not finished.  

> Amazon to default to Gnome

That's a very good question.   

It will be nice to know, if the user can simply change the target desktop setting to xfce4, gnome, or mate and the role takes care of everything else, installs the packages, etc.

If gnome works fine, then perhaps it's more consistent with the current configuration to choose gnome.    A slight preference for this.

However, if mate has clear advantages, it could be mate.    Open to the idea.   (in that case, the variable vnc_desktop in defaults/main.yml would have to be migrated to all the vars/ files instead, to be set per OS, as was done with vnc_server.)

**Comment by sdarwin** [comment]
"Rocky Linux", and "Amazon Linux 2" have each been add/merged to master, as separate commits.    CI tests are passing.  Test kitchen 'manual' testing seemed to go fine.  If you discover any bugs, let me know, we can continue to update.   

Thanks for all the help.  Closing this PR.

**Pull request closed without merging**
