### PR TITLE
Add initial support for Amazon Linux 2, Rocky and Debian

### PR DESCRIPTION
**Pull request by mikedlr**
I wanted to get this working on AWS Linux - this is the pull request that gets that started working.  I think it needs more work so probably you will want to comment before merging?

### CODE REVIEW

**Comment by sdarwin** [comment]
Hi Mike,

Thanks for the PR.    It's a possibility.

Comments:  

- You've changed the epel section to skip Amazon Linux.  Ok. That's fine.  The next question though, if installing specifically RedHat, I am not sure about adding "ignore_errors: True".    If based on the earlier testing, epel was a requirement, it would be good to catch the error right where it happens, and not ignore it.  ?  This wouldn't affect Amazon Linux.    

- A few of the other Redhat vars files included the package group "@Server with GUI".   Did you discover that amazonlinux doesn't have, or doesn't require these packages, for VNC to run?

- Add amazonlinux in .github/workflows/ci.yml  .   Existing tests are based on "geerlingguy" docker images, and he has amazonlinux2  https://github.com/geerlingguy/docker-amazonlinux2-ansible

- The role is designed to support a few combinations of  different desktops and VNC servers.   It's not an absolute requirement they all work, but we should know which combinations are successful and which aren't.  And then, if a problem is discovered, make an attempt to fix it.   Annotate info about failed tests at the end of the docs/admin-guide.md file.    A good method to run tests is [Test-Kitchen](https://github.com/neillturner/kitchen-ansible) .  Notice the .kitchen.yml file in this repo.    If figuring out Test-Kitchen is overly time consuming, no problem, an equivalent alternative is to manually launch 4 or 6 or 8 EC2 instances with amazonlinux2 , test the ansible role for each different combination:  (xfce4 + tigervnc.  gnome + tigervnc. etc)       Which ones succeed? Which ones fail?

**Comment by mikedlr** [comment]
* On the EPEL install, there are other roles for installing EPEL - some of these have more clever handling of more complex situations and will work when the existing EPEL rule might not.  In this case, having the rule fail will block some installs that might work otherwise. I can see that requiring EPEL install via a separate role would be a hassle and also that building the full complexity of e.g. robertdebock.epel would over-complicate the code. Perhaps there should be a variable or tag to skip EPEL install if needed? 
* amazonlinux doesn't have "@server with GUI" and attempting to install it breaks the install;  I haven't yet checked for @xfce which is listed below.  
* I've gone through all places where I think that there should be additions to test etc. configuration however I don't have a kitchen set up or know the tool.  Trying to investigate a bit.

**Comment by sdarwin** [comment]
That explanation for making epel optional sounds "plausible".  However, a higher bar for making a change would be to ask: "In your own company, or your own project, did you actually run into a problem, where you couldn't install epel on redhat?"  really? And what solution did you finally discover?  (if epel packages were required).    It is not clear that robertdebock is doing anything beyond a regular install.   
 https://github.com/robertdebock/ansible-collection-roles/blob/master/roles/epel/tasks/main.yml
 
Although, for amazon, a different command entirely?
```
sudo amazon-linux-extras install epel
```
https://forums.aws.amazon.com/message.jspa?messageID=824182

>  I don't have a kitchen set up or know the tool. 

The main advantage of test kitchen, is you can launch a bunch of ec2 instances, and run ansible on them in parallel.  That's a quick way to test a matrix of various configurations.     Expect to spend a few days learning test-kitchen though.   Up to you.    So, it's not required.   The same result can be achieved by manually launching instances, and running ansible on them.

 > amazonlinux doesn't have "@server with GUI" and attempting to install it breaks the install;

That is beginning to remind me... 

When first building this role, a while ago, I might have tested amazonlinux.   And, "@server with GUI" wasn't available.  And, VNC was not functioning correctly.   And, the role was not installing correctly.

How far have you gotten with testing VNC on amazonlinux?    

The initial commits you added to the pull request,   did they result in a working system, where VNC is up and running?

**Comment by mikedlr** [comment]
I won't have time at the present moment to get the full test-kitchen setup installed ; would have to have something around Travis  / GitHub actions already working before doing that.  I am testing some other things so I will be semi-manually testing configurations on other operating systems such as Rocky Linux and will report any results. Hopefully at some point soon I will get a time and place to play with the full test-kitchen and understand the benefits. 

As far as VNC goes, I have it working fine although I currently seem to have the wrong user turning up on the first desktop and no session running (it just pops up a plain xterm) 

These instructions also worked fine manually 
* https://aws.amazon.com/premiumsupport/knowledge-center/ec2-linux-2-install-gui/ 

I do notice that desktop environments other than mate seem to be broken in AWS Linux though.  Given that Amazon Workspaces uses the mate desktop I guess that shouldn't be surpsising?

**Comment by mikedlr** [comment]
I've added Debian and Rocky Linux as well.  I can easily split this into separate PRs if that would help with merging it.

**Comment by sdarwin** [comment]
If adding more operating systems, they should also be included in the file .github/workflows/ci.yml

**Comment by sdarwin** [comment]
If adding more operating systems, they should also be included in the file .github/workflows/ci.yml.   

The Github Actions tests https://github.com/sdarwin/Ansible-VNC/actions need to be passing before a merge. 
 Achieving passing tests might require a few iterations.  Pushing multiple commits.  Therefore, I'd recommend that you make another branch in your own local git repo, such as:

```
git checkout -b feature/testing-amazon-linux
```

Then, you can push multiple times to mikedlr:feature/testing-amazon-linux, and debug the failures in CI.   And, debug amazon linux.   When ready, merge back into this pull request branch.   Report that "all tests passing, and it's ready".

Github Actions might not run on the feature/testing-amazon-linux branch without modifying ci.yml:

```
  push:
    branches:
      - master
      - develop
      - feature/*
```

**Comment by sdarwin** [comment]
rockylinux failing tests because the user isn't available.  Create the user in tests/createusers.yml

**Comment by mikedlr** [comment]
Took me a little while to figure out the settings to get the actions running in my account and fix, but now CI is green for me.  

There is still a problem that the included .vnc/xstartup file causes a failure of the GUI on Debian with a dialog box coming up and forcing logout. Simply disabling the file (`mv .vnc/xstartup .vnc/xstartup.disable`)  makes the session work.  I _think_ the problem is the lack of a dbus daemon running. 

Given that the system works without an xstartup, I guess there has to be some other logic behind using one?  Would it be wrong to just not install the file under systems where it doesn't work?

**Comment by sdarwin** [comment]
> xstartup file causes a failure of the GUI on Debian 

- This is only on Debian 11, and not other versions of Debian?

- Let's say you don't create an xstartup file on a new system. Then, stop and start VNC.  Does it generate an xstartup file?   If so, compare what it generates with what the ansible role installs.  Can a very small section be added or removed that would reconcile the two files.

**Comment by sdarwin** [comment]
I have just tested Ubuntu 20. There are 3 options on that OS:
- gnome settings, per this role.
- xfce settings, per this role.
- No xstartup file.  A default desktop, which looks different than the others, is displayed.

We may want to offer all three choices.   Add a new variable, "create_xstartup_file".  If that must be false on Debian 11, it's an option.   However,

Does xfce work on Debian 11?  
Run vncserver with -verbose flag.  Try to debug xstartup file.  It will be preferable to have all choices available, and not be forced to delete xstartup.   Since it's an ansible template, it can be customized (a little bit) for each operating system.

**Comment by sdarwin** [comment]
@mikedlr , the problem is larger than expected.    

https://github.com/TigerVNC/tigervnc , major changes in the implementation when upgrading from 1.10 to 1.11 .

**Comment by sdarwin** [comment]
- detect version of tigervnc
- depending on version of tigervnc, have a different set of tasks. Namely, configure ~/.vnc/config instead of ~/.vnc/xstartup.   
- if the number of changes is extensive, they could be moved into separate yaml files, and then "included".   This would keep a clean separation of logic.  

I will take a look sometime soon, I hope they haven't really broken everything.

**Comment by sdarwin** [comment]
This Debian 11/tigervnc major rewrite should be moved into a separate pull request, based on the master branch, not connected to rocky or amazon-linux.    First half of tasks/main.yml stays more or less the same.  Second half of tasks/main.yml could be two "blocks", based on a variable vnc_paradigm=version1 or version2, which should be computed and/or set in the config.   In the new version2 paradigm, don't create vncstart and vncstop.  Don't create xstartup.   Skip the earlier systemd steps also.   Instead, follow new requirements:

- Add all users in /etc/tigervnc/vncserver.users
- create .vnc/config files
- Start and stop services for all users like this (where :1 is the respective connection)
```
systemctl enable tigervncserver@:1.service
systemctl start tigervncserver@:1.service
```

**Comment by mikedlr** [comment]
I have now tested Debian 10.  The session on Debian 10 _does_ start, however it is severely broken.  II can see the gnome-session process running. Some form of window manager is running with window decoration etc. However there is no menu or search function etc.  I'd consider that to be broken.  

Based on that I agree about splitting Debian fixes off into a separate pull request, however I think that the fix should probably be different and involve simply not using the session.

**Comment by mikedlr** [comment]
This pull request is replaced by https://github.com/sdarwin/Ansible-VNC/pull/15 and https://github.com/sdarwin/Ansible-VNC/pull/17

**Pull request closed without merging**
