### PR TITLE
pre-commit file

### PR DESCRIPTION
**Pull request by mikedlr**
This is a pre-commit file which will make it easy for people who want to enforce linting to do that. Please could you add it to the repo.  This is completely opt-in in the sense that, if you don't do install pre-commit and then do `pre-commit install` nothing will happen, however it's also easy to add to the build if you want to enforce more rules using pre-commit.   

Also included Pipfile and Pipfile.lock which make it easy to use pipenv for development here.  This pull request is the first in a series.

### CODE REVIEW

**Comment by sdarwin** [comment]
need to preserve trailing whitespace in markdown file, they are used to force a line break.

```
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
```

**Comment by mikedlr** [comment]
I have rewritten this PR to be merged first.  Please comment or merge.  My other PRs ( one for Amazon and Rocky and then a separate one for Debian) will be based off this one.

**Comment by sdarwin** [comment]
Checked in .pre-commit-config.yaml 

I am not yet convinced it makes sense to add more files, lock files, just to be able to install one optional pip package on your dev machine...

**Comment by sdarwin** [comment]
ok, you added a thumbs up.   most users are not dev contributors, and we don't want to confuse the average user with more configs than are necessary.  closing issue, for now.

**Pull request closed without merging**
